language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache
    - "~/google-cloud-sdk"

services:
  - postgresql

addons:
  postgresql: "9.6"
  hosts:
    - postgres.retrofeed
    - retrofeed.retrofeed

env:
  global:
  - ENV=TEST
  - PATH=$PATH:~/google-cloud-sdk/bin
  - PGSSLMODE=require
  - GCP_STAGING_PROJECT=chmsqrt2-retrofeed-staging
  - GCP_STAGING_ZONE=europe-west1-b
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GOOGLE_APPLICATION_CREDENTIALS=config/gcp-ci-builder-key.json
  # CYPRESS_RECORD_KEY
  - secure: "2J3dlJO+D+WltkF2pMe5PiIDBDS7lPc4bxQNNIfDaB5CwHhtj6jl/+5sQslIWBQym/S5hoTW72iyTS1QQqasET8W6JW8rpSsaQ7PiDfYiC3na0KNgjmejOc62GRobHcH8cRMCRox/ArnMkbRSnVZplTAayq5kfDHRXMkOeMFSW7D0b8G6jJ8oYUXzRTfV+mAazdzRPHcZ8kbQN6vfG14Ne7UzlV69XQRDdF9xiTmTbZM2sT+z4vi6/VpYVifVPZkApoqAeL6+FDchpT30jUC89Rf9JthEZ3ion2QuaDtchwSwjGp7jzprj5dC196Bd8csUyjnqYN+E4fub/3d9v/pbtC78OHuubnm9wO/N9XEbWW9Ppe5/0Pl8/m41NV9ElY5ElV9wOu4Z8dWUASho/IW7Lbr/sT50ASGjjHi7tYEodEoH3gzdjKARZC5OdVsMkK918mPYJxTZO8gJrqDtpOYkbE0klvfMY5qVPVuGTGJxkRZ70MJWbGeQ83zOYuLOwtAz0+DlsXVAWtFUj5btc0/ZrcmE3m1NOUHrCMDYJCIcyJidkzdBkCu6+byB+Vn+yr+00UrJL7qHAnZz7YtYwYGrK3Wr/n+A2lQl9mPusMLakRLs4FEvQDnZvpAUGmr7p9dqZVpIkvaMop6OWGHEhM3130tOaeEhgkLJI/pDrIG/U="

before_install:
- if [ ! -d ~/google-cloud-sdk/bin ]; then
    rm -rf ~/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts;
    ~/google-cloud-sdk/bin/gcloud -q components update kubectl;
  fi
- source ~/google-cloud-sdk/path.bash.inc

install:
- yarn install

before_script:
- psql -c "create database retrofeed;" -U postgres
- psql -c "create user service_core with password 'Mvuph9hLL7iCbpKZBEWYlLEaJJhBju2GBmxfpZom';" -U postgres
- psql -c "grant all on database retrofeed to service_core;" -U postgres
- openssl aes-256-cbc -K $encrypted_29fa2914873b_key -iv $encrypted_29fa2914873b_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- yarn migrate
- yarn compile
- cd compile; ls -lah; ls -lah server/controllers; ls -lah server/controllers/app; yarn start &
- sleep 30
- cd ..

script:
- yarn lint
- yarn test:unit
- yarn test:e2e

after_success:
- ./scripts/send-coverage.sh

deploy:
  - provider: npm
    email: horia141@gmail.com
    api_key:
      secure: "xgG+S45t6IXMIp7/kjPFjJaqgQkak1ap1qgfMK9uEY+pPAhQlXWTDoDGISor4Py4N0ABDy17ssPVCRRonwpi78lb68Dj4a6FNHjxC5p+yxjd4HaxHGpf3KqsiBfP38h/uw3uicdnOhgqQuB5kJJMp9OkhQHwcZRh2co2Qvp2vBqOqN7ERHT2TFZ/XqrsZuTrlgZLfd0G9ns6uuV2rqh3Wor8uqSe5acuRPE5q8K+NYZR6JvA4i1G3PMwpkFnVMYgALSwidWfxFoqSHZrH1DZTBlyR+3AN4wAMMHse4Yn0aMNDj8/esNRIMO3lfBwUsFuuf3FufIm8EFn8dhvhSjr4eGTjp5I/iCaglVYuoo9PM9wobxbvvupO39eXge11F6VI9PWxrDCb4pVI9a6/InqDwMGkMhFMpHFwg45RmNF8mdFSToHpCXsrZhNakV7WSS3qe6Uxjp6MhTI+ZQyHO8NAiEvDfuYiqRlI7HHbA+3Ow+Mj19EncyNokxbAnilDr+Ax3tmgXsVGlecfU9xLMw1MpbEEHRAEqpLcxuu2lb7FyKlUqR/xzFZlNzeTXtiwMFFbHMEXO2tx89uRvXt2lmb1RDZMWSyMcZbNw/xI9625wZbPQWqz1bZQZwuMimvP3f88RnzuRstfYy/X3LzZx5auPNHMj4yvzqdNhd1QO7UDfA="
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-registry.sh ${GOOGLE_APPLICATION_CREDENTIALS} ${TRAVIS_TAG}
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy-prelive.sh ${TRAVIS_TAG}
    on:
      tags: true
