language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk"

services:
  - postgresql

addons:
  postgresql: "9.6"
  hosts:
    - postgres.retrofeed
    - retrofeed.retrofeed

env:
  global:
  - ENV=TEST
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - PGSSLMODE=require
  - GCP_STAGING_PROJECT=chmsqrt2-retrofeed-staging
  - GCP_STAGING_ZONE=europe-west1-b
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GOOGLE_APPLICATION_CREDENTIALS=config/gcp-ci-builder-key.json
  # CYPRESS_RECORD_KEY
  - secure: "2J3dlJO+D+WltkF2pMe5PiIDBDS7lPc4bxQNNIfDaB5CwHhtj6jl/+5sQslIWBQym/S5hoTW72iyTS1QQqasET8W6JW8rpSsaQ7PiDfYiC3na0KNgjmejOc62GRobHcH8cRMCRox/ArnMkbRSnVZplTAayq5kfDHRXMkOeMFSW7D0b8G6jJ8oYUXzRTfV+mAazdzRPHcZ8kbQN6vfG14Ne7UzlV69XQRDdF9xiTmTbZM2sT+z4vi6/VpYVifVPZkApoqAeL6+FDchpT30jUC89Rf9JthEZ3ion2QuaDtchwSwjGp7jzprj5dC196Bd8csUyjnqYN+E4fub/3d9v/pbtC78OHuubnm9wO/N9XEbWW9Ppe5/0Pl8/m41NV9ElY5ElV9wOu4Z8dWUASho/IW7Lbr/sT50ASGjjHi7tYEodEoH3gzdjKARZC5OdVsMkK918mPYJxTZO8gJrqDtpOYkbE0klvfMY5qVPVuGTGJxkRZ70MJWbGeQ83zOYuLOwtAz0+DlsXVAWtFUj5btc0/ZrcmE3m1NOUHrCMDYJCIcyJidkzdBkCu6+byB+Vn+yr+00UrJL7qHAnZz7YtYwYGrK3Wr/n+A2lQl9mPusMLakRLs4FEvQDnZvpAUGmr7p9dqZVpIkvaMop6OWGHEhM3130tOaeEhgkLJI/pDrIG/U="

before_install:
- if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
    rm -rf ${HOME}/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts;
    ${HOME}/google-cloud-sdk/bin/gcloud -q components update kubectl;
  fi
- source ${HOME}/google-cloud-sdk/path.bash.inc

install:
- yarn install

before_script:
- psql -c "create database retrofeed;" -U postgres
- psql -c "create user retrofeed with password 'retrofeed';" -U postgres
- psql -c "grant all on database retrofeed to retrofeed;" -U postgres
- yarn migrate

script:
- yarn lint
- yarn test
- yarn serve &
- sleep 30
- yarn test:e2e

after_success:
- ./scripts/send-coverage.sh

deploy:
  - provider: npm
    email: horia141@gmail.com
    api_key:
    - secure: "ksOVi5wVazRYav6GzWlv9ho4VSV9azGDkRmGj7pimf2qc1prylmq1LDyqwtxxFdnFqmk8uIBTWVCUfenPZ5kUXfWK+C8S7gjTYKXltnRCuvQhhAk0NgXxLFBBk3bZikuiKkhWEUdWzr4nWeoLnCLzn+eteP30VBmMCGE+MNmWR3iGtLR3UccjjTXdL0WTGy+HmLmWY0iXsKWTW7t5QBSENVaZLz8ALboQWYUWIbFX2kC6Ek3TKGPnJocS2voZTirZQVKNQ/mfQIGsdTZXwDW4tgJbwFlZWgWO/6XLR+mleOaIYNxILnDatNokbIQeM3qXp3JWGqJtl0hD1X/4Z8GO3Zx4aTB1ub+Ky/frPO+/vq1ZwzV68w8/PFm/Uh4HYhe+FscVpFq6HcANyGBe9BJRqdRXwYFoGOEJfzpD4JNCbee1k9eJ4bCllxNUwUoO1riCTSP+1yzuaYKZf8oEtrWfF/UT9kH3bLV8noWYzH6EDD3trKHIgncvxKSEd6nlfdUJNUISXSni7bq3oUwkjkBREBeeM93cnPgTJgIDvYUaJRvSEYx6iRTkec701lLMRf5EVv0LQVJg/Npar4583PLltzMJrUE1ItmnbWGXDVWLBqgccu4JMIonRmpYIR5RrBENX/6+fvvIaEANGTMHTJ4NjRs4u80qx6W/xA18vohLpA="
    on:
      tags: true
